//! modernbert smoke: loads the committed `tests/fixtures/tiny_modernbert/`
//! (generated by `xtask-generate-tiny-modernbert`), tokenizes a short input,
//! runs a ModernBERT forward pass, and asserts the last hidden state has the
//! expected shape. Verifies the candle modernbert wire-up across all 3
//! supported platforms with no network access (fixture lives in repo).

use std::path::PathBuf;

use anyhow::{Result, anyhow};
use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use candle_transformers::models::modernbert::{Config, ModernBert};

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("tiny_modernbert")
}

#[test]
fn modernbert_forward_returns_hidden_size_embedding() -> Result<()> {
    let dir = fixture_dir();
    let config: Config = serde_json::from_slice(&std::fs::read(dir.join("config.json"))?)?;
    let tokenizer = tokenizers::Tokenizer::from_file(dir.join("tokenizer.json"))
        .map_err(|e| anyhow!("load tokenizer: {e}"))?;

    let device = Device::Cpu;
    let weights_path = dir.join("model.safetensors");
    // SAFETY: `from_mmaped_safetensors` requires that no other process
    // truncates or modifies the file while the mmap is live. The fixture is
    // committed to the repo as read-only test data and never mutated at
    // runtime.
    //
    // Unlike production weights (loaded via `safetensors::load` + rename in
    // `src/embedding/ruri_v3.rs`), the fixture is emitted by
    // `xtask-generate-tiny-modernbert` with `model.*`-prefixed keys already,
    // so no renaming is needed here.
    let vb = unsafe { VarBuilder::from_mmaped_safetensors(&[&weights_path], DType::F32, &device)? };
    let model = ModernBert::load(vb, &config)?;

    let encoding = tokenizer
        .encode("hello world", true)
        .map_err(|e| anyhow!("encode: {e}"))?;
    let ids: Vec<u32> = encoding.get_ids().to_vec();
    let mask: Vec<u32> = encoding.get_attention_mask().to_vec();
    let seq_len = ids.len();

    let input_ids = Tensor::new(ids.as_slice(), &device)?.unsqueeze(0)?;
    let attention_mask = Tensor::new(mask.as_slice(), &device)?.unsqueeze(0)?;

    let output = model.forward(&input_ids, &attention_mask)?;
    let dims = output.dims();
    assert_eq!(
        dims,
        &[1, seq_len, config.hidden_size],
        "expected [1, {seq_len}, {hidden}], got {dims:?}",
        hidden = config.hidden_size
    );
    Ok(())
}
